theme: jekyll-theme-modernist
title: Roark Habegger
email: roarkhabegger@gmail.com
collections:
   projects:
     title: Research Projects
     link: /projects/
     display: true
     output: true
   notes:
     title: Course Notes
     link: /notes/
     display: true
     output: true
   life:
     title: Life Outside 
     link: /life/
     display: true
     output: true
   astroA_grad:
     display: false
     output: true
   astroB_grad:
     display: false
     output: true
   cm_grad:
     display: false
     output: true
   cm_ug:
     display: false
     output: true
   cosmo_grad:
     display: false
     output: true
   em_grad:
     display: false
     output: true
   em_ug:
     display: false
     output: true
   gals_grad:
     display: false
     output: true
   ism_grad:
     display: false
     output: true
   obs_grad:
     display: false
     output: true
   qm_grad:
     display: false
     output: true
   qm_ug:
     display: false
     output: true
   stars_grad:
     display: false
     output: true
   sm_ug:
     display: false
     output: true

#   Python:
#     output: true
#     sort_by: lessonNum
#   Stellar:
#     output: true
#     sour_by: lessonNum
