theme: jekyll-theme-modernist
title: Roark Habegger
email: roarkhabegger@gmail.com
collections:
   projects:
     link: /projects/
     display: true
     output: true
   notes:
     link: /notes/
     display: true
     output: true

#   Python:
#     output: true
#     sort_by: lessonNum
#   Stellar:
#     output: true
#     sour_by: lessonNum
