theme: jekyll-theme-modernist
title: Roark Habegger
email: roarkhabegger@gmail.com
collections:
   projects:
     name: Research Projects
   notes:
     name: Astrophysics Notes
  
#   Python:
#     output: true
#     sort_by: lessonNum
#   Stellar:
#     output: true
#     sour_by: lessonNum
