theme: jekyll-theme-modernist
title: Roark Habegger
email: roarkhabegger@gmail.com
collections:
   projects:
     name: Research Projects
     #url: /projects/
     output: true
   notes:
     name: Astrophysics Notes
     #url: /notes/
     output: true

#   Python:
#     output: true
#     sort_by: lessonNum
#   Stellar:
#     output: true
#     sour_by: lessonNum
