theme: jekyll-theme-modernist
title: Roark Habegger
email: roarkhabegger@gmail.com
collections:
   projects:
     title: Research Projects
     link: /projects/
     display: true
     output: true
   notes:
     title: Course Notes
     link: /notes/
     display: true
     output: true
   qm_grad:
     title: Graduate Quantum Mechanics
     link: /notes/qm_grad/
     display: False
     output: true
   cm_grad:
     title: Graduate Classical Mechanics
     link: /notes/cm_grad/
     display: False
     output: true

#   Python:
#     output: true
#     sort_by: lessonNum
#   Stellar:
#     output: true
#     sour_by: lessonNum
